[theme]
primaryColor = "#8A2BE2"        # Violet Néon
backgroundColor = "#0E1117"     # Noir Profond
secondaryBackgroundColor = "#181b21" # Gris très foncé (Cards)
textColor = "#E0E0E0"           # Blanc cassé
font = "sans serif"
base = "dark"